SELECT count (Position) FROM HRDataset_v14 WHERE Position = "Production Technician I";
SELECT count (GenderID) FROM HRDataset_v14 WHERE GenderID = "1";
SELECT count (ManagerName) FROM HRDataset_v14 WHERE ManagerName = "Michael Albert";
SELECT count (EmploymentStatus) FROM HRDataset_v14 WHERE EmploymentStatus ="Active";
SELECT count (EmploymentStatus)  , MaritalDesc FROM HRDataset_v14 WHERE EmploymentStatus = "Active" and MaritalDesc = "Married";
SELECT count (EmploymentStatus) , Salary FROM HRDataset_v14 WHERE EmploymentStatus = "Active" and (Salary <= 600000);
SELECT max (Salary)FROM HRDataset_v14;
SELECT (Position) FROM HRDataset_v14 WHERE Salary >= 250000;
SELECT avg (Salary) FROM HRDataset_v14 ;
SELECT (Position) FROM HRDataset_v14 WHERE Salary <= 69020.684887459;
SELECT (Position) FROM HRDataset_v14 WHERE Salary <= 69020.684887459 and EmpSatisfaction<= 2;
SELECT Employee_Name FROM HRDataset_v14 WHERE PerfScoreID>=3;
SELECT EmpStatusID,Employee_Name FROM HRDataset_v14 WHERE EmpStatusID = 5;
SELECT count (Department)FROM HRDataset_v14 WHERE Department = "IT/IS";
SELECT Department, count (Department) FROM HRDataset_v14 GROUP by Department;
SELECT Position,RecruitmentSource FROM HRDataset_v14 WHERE Salary >= 250000;
SELECT count (TermReason) FROM HRDataset_v14 WHERE TermReason = "unhappy";
SELECT Position,count (Position) FROM HRDataset_v14 GROUP by Position;
SELECT Position,State FROM HRDataset_v14 WHERE Position = "Data Analyst" AND State = "MA";
SELECT CitizenDesc,RecruitmentSource FROM HRDataset_v14 WHERE CitizenDesc = "US Citizen" AND RecruitmentSource = "Diversity Job Fair";
SELECT TermReason FROM HRDataset_v14 WHERE TermReason = "career change";
SELECT TermReason,count (TermReason) FROM HRDataset_v14 WHERE EmploymentStatus = "Voluntarily Terminated" GROUP BY TermReason ;
SELECT count (EmploymentStatus) FROM HRDataset_v14 WHERE EmploymentStatus = "Voluntarily Terminated" ;
SELECT count (EmploymentStatus) FROM HRDataset_v14 WHERE EmploymentStatus = "Terminated for Cause";
SELECT count (EmploymentStatus) , Department FROM HRDataset_v14 WHERE EmploymentStatus = "Active" GROUP BY Department;
SELECT count (EmploymentStatus),State,Department FROM HRDataset_v14 WHERE EmploymentStatus = "Active" GROUP BY State;
SELECT (ManagerName), Department,RecruitmentSource,EmploymentStatus FROM HRDataset_v14 WHERE Department = "IT/IS" AND EmploymentStatus == "Active" AND RecruitmentSource = "Diversity Job Fair";
SELECT RecruitmentSource, count (EmploymentStatus) FROM HRDataset_v14 WHERE EmploymentStatus = "Terminated for Cause" GROUP BY RecruitmentSource ;
